<?php

namespace AppBundle\Repository;

/**
 * president_userRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class president_userRepository extends \Doctrine\ORM\EntityRepository
{

}
