<?php

namespace AppBundle\Repository;

/**
 * PresidentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PresidentRepository extends \Doctrine\ORM\EntityRepository
{
}
