# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
            Symfony\Component\Security\Core\User\User:
                algorithm: bcrypt
            AppBundle\Entity\president_user:
                algorithm: bcrypt


    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        in_memory:
            memory:
              users:
                admin:
                  password: $2y$13$Bp6yhaVaYulKLroisDQZ3uVTbP1gO7Z7tigLjMtGb7gAABlBkoVfe
                  roles: 'ROLE_ADMIN'
        db_provider:
            entity:
              class: AppBundle:president_user
              property: presidentCode

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            provider: db_provider
            form_login:
                   login_path: login
                   check_path: login
                   default_target_path: /president/detail
            logout:
                    path: /logout
                    target: /login


            anonymous: ~
    access_control:
       - { path: ^/president/detail, roles: ROLE_USER }
       - { path: ^/president/edit, roles: ROLE_USER }
            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~
