AppBundle\Entity\test:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\testRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
            nullable: true
    lifecycleCallbacks: {  }
